### PR TITLE
Monocle Layout "minimize unfocused windows" fix and improvements

### LINKED ISSUE #43: "Minimize other windows in Monocle layout" should only minimize windows on the same monitor
Got a fix for this incoming in a PR...

### PR DESCRIPTION
**Pull request by bladedvox**
## Summary

Fixes Monocle Layout with `Minimize Unfocused Windows` (internally `config.monocleMinimizeRest`) option enabled.

Restores previous functionality (before Wayland patches) and adds
* minimize inactive windows only on same monitor with multimonitor setup
* can switch windows with focus-changing `Actions`
* switches to the next window when closing the active window (still a little buggy in multimonitor, but a big improvment)
* handles moving window onto a `Surface` with this layout properly

## Breaking Changes

None

## UI Changes

Removed "(WIP)" from "Minimize unfocused windows" option in the config UI.

## Test Plan

1. Reload script
2. Verify all behavior in the Summary

## Related Issues

Closes #43, #55

### CODE REVIEW

File: src/engine/layout/monocle_layout.ts [hunk 1]
```diff
@@ -54,7 +54,9 @@ export default class MonocleLayout implements WindowsLayout {
         const current = controller.currentWindow;
         if (current && current.tiled) {
           tiles.forEach((window) => {
-            if (window !== current) {
+            if (window !== current
+              && (window.window as KWinWindow).client.screen
```
Comment (gikari) [inline src/engine/layout/monocle_layout.ts:58]: It's better to move the screen getter and minimized property into the window interface:
```typescript
export default class Window {
// ...
public get screenNumber(): number {
    return this.window.screenNumber;
}
// ...
}
```
This avoids casting and respects [SOLID](https://en.wikipedia.org/wiki/SOLID).

**Comment by gikari** [comment]
Could you also change your commit messages to respect [CC](https://www.conventionalcommits.org/en/v1.0.0/)? I should probably implement CI check for this in the future.

File: src/engine/layout/monocle_layout.ts (hunk 1 above)
Comment (bladedvox) [reply src/engine/layout/monocle_layout.ts]: Ok, I got it to build changing as you suggested, I will test tonight and reopen if it works properly.

**Comment by bladedvox** [comment]
@gikari I've got the original functionality restored. It's kind of hacky but the only way I could find to do it. Basically I added a hook to `controller.onWindowFocused()` to do the minimization under the correct layout (and if the setting is enabled). I also had `controller.showNotification()` raise the event as well so that it works properly when first changing to the Monocle layout.

How do you want to handle the finer points?
* Should we enable this by default?
* Should we make an exception for the focus cycle (or add a separate Action) that includes minimized windows in the queue when switching focus?

File: src/controller/index.ts [hunk 2]
```diff
@@ -334,6 +340,20 @@ export class TilingController implements Controller {
 
   public onWindowFocused(window: Window): void {
     window.timestamp = new Date().getTime();
+    const self = this;
+    this.currentWindow = window;
+
+    if (this.engine.currentLayoutOnCurrentSurface() instanceof MonocleLayout &&
```
Comment (gikari) [inline src/controller/index.ts:346]: This is the "business logic" of tiling. It needs to be inside the engine. The controller is responsible only for input and events handling and sometimes the validation of the data from the driver. It is similar to MVC pattern (or MVVM) - the controller is a middleman between the model (in our case engine) and the view (in our case the driver).

**Review by gikari — CHANGES_REQUESTED** [review]
> Should we enable this by default?

Not yet. If it works well - we probably should in the future.

> Should we make an exception for the focus cycle (or add a separate Action) that includes minimized windows in the queue when switching focus?

We have FocusNextWindow and FocusPreviousWindow. Those should work with this option on as in before. As for Focus Left, Right and so on, I am not sure. How do those work in classic tilings WMs with monocle layout (It seems like Monocle is the terminology, that comes from dwm)?

File: src/controller/index.ts [hunk 3]
```diff
@@ -193,6 +195,10 @@ export class TilingController implements Controller {
 
   public showNotification(text: string): void {
     this.driver.showNotification(text);
+    const self = this;
```
[the remark this answers is not in the document]
Comment (bladedvox) [reply src/controller/index.ts:198]: Ah, that was left over from a previous attempt at implementing. Good catch, it isn't necessary anymore.

File: src/controller/index.ts (hunk 2 above)
Comment (bladedvox) [reply src/controller/index.ts:346]: Ok, I'll move it into an `engine` method.

**Comment by bladedvox** [comment]
I will address the comments you raised today -- as for the keyboard shortcuts, it's been a long time since I used DWM, but looking at the source code now it seems that it doesn't implement minimization at all. I currently like the behavior we have of cycling only through visible windows with the `FocusNext/PrevWindow` actions. I use a keybind for a task switcher that cycles through minimized windows only if I need to quickly get access to one, and is how I currently switch focus by keyboard in Monocle mode with the `monocleMinimizeRest` option enabled.

I think, just to avoid needing a separate keyboard shortcut, we should either
a. include minimized windows for consideration in `FoucsNext/Prev`
b. add an optional argument to `engine.focusOrder()` that is used in MonocleLayout (when this option is enabled) when overriding `FocusNext/Prev/Bottom/Upper/Left/Right` that includes minimized windows for consideration

I lean towards `b` since I like the current focus switching model.

**Comment by gikari** [comment]
>  it's been a long time since I used DWM, but looking at the source code now it seems that it doesn't implement minimization at all. 

I meant if the switching between windows in monocle mode works with Next/Previous window shortcuts. If it is, we should do the same, but we can provide an option to exclude minimized windows from the list.

**Comment by bladedvox** [comment]
Using this branch on my machine and so far so good. Here's some notes on the behavior:

Assuming monocle layout and `config.monocleMinimizeRest == true`:
* You can switch windows with the `WindowFocusNext/Prev/Right/Left/Upper/Bottom` Actions
* Closing the active window switches to the next window
* Floating windows on the `DriverSurface` are handled properly
* Moving a tiled window into the workspace/screen results in it being the only visible window
There is still an issue with using this layout in a multi-monitor setup -- if you close the active window in Monocle layout in your secondary monitor, it switches to a window in the primary monitor instead of the same monitor that the closed window was in. I Haven't really figured out why this is happening. I have some code that *tries* to fix it but it isn't really working. Will update with progress on that. Other than that minor issue, I am comfortable with the experience so far.

**Comment by bladedvox** [comment]
I see the failing tests. Edited the `action.test` locally and will rebase/reword to shorten my commit messages.

**Comment by gikari** [comment]
> I see the failing tests. Edited the `action.test` locally and will rebase/reword to shorten my commit messages.

Could you also please update the MR description according to the [new template](https://github.com/gikari/bismuth/blob/master/.github/pull_request_template.md) please?

**Comment by bladedvox** [comment]
PR description updated, hope it's all up to standard :)

File: src/controller/index.ts [hunk 4]
```diff
@@ -334,6 +347,17 @@ export class TilingController implements Controller {
 
   public onWindowFocused(window: Window): void {
     window.timestamp = new Date().getTime();
+    this.currentWindow = window;
+    // Minimize other windows if Moncole and config.monocleMinimizeRest
+    if (this.engine.currentLayoutOnCurrentSurface() instanceof MonocleLayout
+      && this.config.monocleMinimizeRest
+      && this.engine.windows.getVisibleTiles(window.surface).includes(window)) {
+      this.engine.currentLayoutOnCurrentSurface().apply(
```
Comment (gikari) [inline src/controller/index.ts:355]: Why do we need to reapply layout?

File: src/engine/index.ts [hunk 5]
```diff
@@ -49,7 +49,7 @@ export interface Engine {
   enforceSize(window: Window): void;
   currentLayoutOnCurrentSurface(): WindowsLayout;
   currentWindow(): Window | null;
-  focusOrder(step: -1 | 1): void;
+  focusOrder(step: -1 | 1, includeHidden: boolean): void;
```
Comment (gikari) [inline src/engine/index.ts:52]: In the future, I'm planning to move the JSDoc comments to the interface. Since you're adding the new parameter, could you add the comment here with the params description?

File: src/engine/index.ts [hunk 6]
```diff
@@ -548,6 +550,12 @@ export class TilingEngine implements Engine {
     );
     if (layout) {
       this.controller.showNotification(layout.description);
+
+      // Minimize inactive windows if Monocle and config.monocleMinimizeRest
+      if (this.currentLayoutOnCurrentSurface() instanceof MonocleLayout
+        && this.config.monocleMinimizeRest && this.controller.currentWindow) {
```
Comment (gikari) [inline src/engine/index.ts:556]:
```typescript
this.currentLayoutOnCurrentSurface() instanceof MonocleLayout && this.config.monocleMinimizeRest
```
is very commonly used. Maybe it is worth creating a wrapper in the engine? Or may be not, because in the future, it will be a good idea to make layouts have their own handlers of events, like `onActivate`, where it will do the layout specific logic, and those hacky checks will go away. What do you think?

**Review by gikari — CHANGES_REQUESTED** [review]
Awesome! :tada: I just tested, and it works very well (except after closing a window in multimonitor it focuses the one, on the other monitor, so after merging you could create an issue for this strange behavior). Just a little small nitpicks (including in-code comments):

I think you can remove WIP it the UI. It still has the multimonitor problem, but I think it works good to be considered WIP feature, and in general marking something WIP in the UI lies not a good impression on the end user.

Also, I apologize for some pasts of CI not working as intended right now. So, could you please format your code with prettier?

And you need to rebase your branch on the current master.

File: src/controller/index.ts [hunk 7]
```diff
@@ -334,6 +347,17 @@ export class TilingController implements Controller {
 
   public onWindowFocused(window: Window): void {
     window.timestamp = new Date().getTime();
+    this.currentWindow = window;
+    // Minimize other windows if Moncole and config.monocleMinimizeRest
+    if (this.engine.currentLayoutOnCurrentSurface() instanceof MonocleLayout
+      && this.config.monocleMinimizeRest
+      && this.engine.windows.getVisibleTiles(window.surface).includes(window)) {
```
[the remark this answers is not in the document]
Comment (bladedvox) [reply src/controller/index.ts:354]: `getVisibleTiles().incudes(window)` is checking that the active window is not floating. Perhaps a shorthand function would be more readable.

File: src/controller/index.ts (hunk 4 above)
Comment (bladedvox) [reply src/controller/index.ts:355]: When switching to a window that has not yet been focused with this layout, this makes sure the window's geometry gets changed when it's unminimized.

File: src/engine/index.ts (hunk 6 above)
Comment (bladedvox) [reply src/engine/index.ts:556]: I think layout handlers are a good idea. As for a wrapper for the meantime, would something like `isMonocleLayoutAndMinimizeRest()` work? It's still verbose but not quite as bad.

**Comment by bladedvox** [comment]
Addressed the issues you mentioned, got the husky hooks set up, verified with ESLint (apparently if you have a default parameter in a function, you don't need to declare its type, good to know) and formatted with Prettier. Rebuilt and restarted KWin for good measure. Everything seems good on my end!

File: src/engine/index.ts [hunk 8]
```diff
@@ -343,42 +350,42 @@ export class TilingEngine implements Engine {
     this.windows.remove(window);
   }
 
-  /**
-   * Focus the next or previous window.
+  /** Focus next or previous window
```
Comment (gikari) [inline src/engine/index.ts:353]: You don't have to duplicate JSDoc here.

**Review by gikari — APPROVED** [review]
Hm, I noticed another thing - if I switch to another layout, the windows, that were minimized by the script are not brought back. I think this, can be addressed in another PR. For now, it is good.
